### PR TITLE
Fixed up some solhint warnings.

### PR DESCRIPTION
**Pull request by jacob-eliosoff**

### CODE REVIEW

**Comment by jacob-eliosoff** [comment]
See the output screenshot in [issue 13](https://github.com/alexroan/USM/issues/13).  I didn't touch Migrations.sol, I didn't shorten the error messages (they don't seem that long!), I didn't scrap the empty constructors (eg `constructor() public ERC20("Minimal Funding", "FUM") {}`), and I ignored the compiler version errors...

**Comment by albertocuestacanada** [comment]
How did you install `solhint`? It's best to install it as a package using `package.json`, which would then be built using `yarn` and run using something like `npx solhint`.

That would allow all of us to use the same tools, and avoid having to set up everything individually for each one.

**Comment by jacob-eliosoff** [comment]
Yeah I did install it that way.  I could include the changes to `package.json`, `package-lock.json` (?) and `.solhint.json` in the PR, they just seemed like a lot of cruft and I hope they're not too specific to my machine/setup...  But I guess I'll do so and you can judge for yourself.  The end result is I just run `npm run solhint`.  I was following https://medium.com/coinmonks/introduction-to-solidity-linting-and-formatting-e838c074791a (just via Google).

**Comment by albertocuestacanada** [comment]
`package.json` and `.solhint.json` should be part of this PR. You can leave `package-lock.json` out.

**Review by albertocuestacanada — CHANGES_REQUESTED** [review]
`package.json` and `.solhint.json` should be part of this PR. You can leave package-lock.json out.

**Comment by jacob-eliosoff** [comment]
Added.

**Comment by albertocuestacanada** [comment]
Happy with it.

 - Disabled the `compiler-version` rule, since we don't know what it does.
 - Disabled the `no-empty-blocks` rule, since there is no alternative.
 - `public` state variables are safe to use (`public` means "readable") and the compiler creates getters for them.

Use `yarn lint:sol` for solidity linting, and `yarn lint:js` for js linting (which auto-fixes).

**Comment by albertocuestacanada** [comment]
Given @jacob-eliosoff absence, and low impact, I'm merging this.

**Pull request merged**
